version: '3.9'

services:

  harbormaster:
    image: strictlyskyler/harbormaster:latest
    ports:
      - "3000:80"
    container_name: harbormaster
    hostname: harbormaster
    restart: unless-stopped
    environment:
      # Required:
      MONGO_URL: ${MONGO_URL}
      ROOT_URL: ${ROOT_URL}
      PORT: 80
      # Optional:
      MAIL_URL: ${MAIL_URL}
      DEBUG: ${DEBUG}
      AMOUNT_SHOWN: ${AMOUNT_SHOWN}
    volumes:
      - ~/.harbormaster:/root/.harbormaster
      - ~/.ssh:/root/.ssh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
